# Medidas Estatísticas

### Imports

In [1]:
import pandas as pd
import numpy as np

### Lendo Dados

In [2]:
df = pd.read_csv("ifood-restaurants-february-2021.csv", sep=",", header=0)

In [3]:
df.head(5)

,availableForScheduling,avatar,category,delivery_fee,delivery_time,distance,ibge,minimumOrderValue,name,paymentCodes,price_range,rating,tags,url
0,False,https://static-images.ifood.com.br/image/uploa...,Marmita,3.99,27,1.22,5300108,10.0,Cantina Arte & Sabor,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ CART::MCHT::100_DELIVE...,https://www.ifood.com.br/delivery/brasilia-df/...
1,False,https://static-images.ifood.com.br/image/uploa...,Açaí,7.99,61,4.96,5300108,10.0,Raruty Açaí Raiz,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ ME...,https://www.ifood.com.br/delivery/brasilia-df/...
2,False,https://static-images.ifood.com.br/image/uploa...,Bebidas,11.99,70,8.35,5300108,5.0,Toma na Kombi,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ R...,MODERATE,0.0,ADDRESS_PREFORM_TYPE $$ CPGN_USER_DISCOUNT_6_L...,https://www.ifood.com.br/delivery/brasilia-df/...
3,False,https://static-images.ifood.com.br/image/uploa...,Carnes,16.49,63,6.35,5300108,20.0,Churrasquinho do Barriga´s,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ NO...,https://www.ifood.com.br/delivery/brasilia-df/...
4,False,https://static-images.ifood.com.br/image/uploa...,Brasileira,11.99,58,5.22,5300108,20.0,Prime Restaurante,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ NOVO,https://www.ifood.com.br/delivery/brasilia-df/...

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 406399 entries, 0 to 406398
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   availableForScheduling  406399 non-null  bool
 1   avatar                  406122 non-null  object
 2   category                406399 non-null  object
 3   delivery_fee            406399 non-null  float64
 4   delivery_time           406399 non-null  int64
 5   distance                406399 non-null  float64
 6   ibge                    406399 non-null  int64
 7   minimumOrderValue       406399 non-null  float64
 8   name                    406399 non-null  object
 9   paymentCodes            406397 non-null  object
 10  price_range             406399 non-null  object
 11  rating                  406399 non-null  float64
 12  tags                    406399 non-null  object
 13  url                     406399 non-null  object
dtypes: bool(1), float64(4), int64(2), object(7)
memory usage: 40.7+ MB

### Selecionando váriaveis relevantes

In [5]:
df_sel = df[[
    "availableForScheduling",
    "category",
    "delivery_fee",
    "delivery_time",
    "price_range",
    "minimumOrderValue"
]]

In [6]:
num = df_sel.select_dtypes(include=['number']).columns.tolist()
cat = df_sel.select_dtypes(include=['object', 'category', 'bool']).columns.tolist()

print("Variáveis Numéricas:", num)
print("Variáveis Categóricas:", cat)

Variáveis Numéricas: ['delivery_fee', 'delivery_time', 'minimumOrderValue']
Variáveis Categóricas: ['availableForScheduling', 'category', 'price_range']

In [7]:
df_sel.describe()

        delivery_fee  delivery_time  minimumOrderValue
count  406399.000000  406399.000000       4.063990e+05
mean        6.804577      47.432747       2.768909e+02
std         4.315815      19.662736       1.570668e+05
min         0.000000      -1.000000       0.000000e+00
25%         4.000000      35.000000       1.000000e+01
50%         6.000000      45.000000       1.500000e+01
75%         9.490000      60.000000       2.000000e+01
max        35.000000    5050.000000       1.000000e+08

In [8]:
df_sel["category"].mode()

0    Lanches
Name: category, dtype: object

In [9]:
df_sel["category"].mode()[0]

'Lanches'

In [10]:
df_sel["availableForScheduling"].mode()[0]

False

In [11]:
df_sel["price_range"].mode()[0]

'CHEAPEST'

In [12]:
for var in cat:
    count = df_sel[var].value_counts()

    if len(count) >= 5:
        print("--------------------------")
        print(f"Coluna: {var}")
        print(f"Moda: {df_sel[var].mode()[0]}\n")
        print(f"{count.iloc[0:5]}\n")
    else:
        print("--------------------------")
        print(f"Coluna: {var}")
        print(f"Moda: {df_sel[var].mode()[0]}\n")
        print(f"{count.iloc[0:5]}\n")

--------------------------
Coluna: availableForScheduling
Moda: False

availableForScheduling
False    404702
True       1697
Name: count, dtype: int64

--------------------------
Coluna: category
Moda: Lanches

category
Lanches          98946
Brasileira       73348
Doces & Bolos    39828
Pizza            36819
Açaí             22110
Name: count, dtype: int64

--------------------------
Coluna: price_range
Moda: CHEAPEST

price_range
CHEAPEST          294140
MODERATE           44769
CHEAP              43100
EXPENSIVE          15778
MOST_EXPENSIVE      8612
Name: count, dtype: int64

### Média e Moda

In [13]:
num

['delivery_fee', 'delivery_time', 'minimumOrderValue']

In [14]:
df_sel['delivery_fee'].mean()

6.804577004372552

In [15]:
df_sel[num].mean()

delivery_fee           6.804577
delivery_time         47.432747
minimumOrderValue    276.890929
dtype: float64

In [17]:
float(df_sel['delivery_fee'].mean())

6.804577004372552

In [ ]:
# Evitar usar laço quando tem uma função built-in no Python

for var in num:
    print(f"Média da coluna '{var}': {float(df_sel[var].mean())}")

Média da coluna 'delivery_fee': 6.804577004372552
Média da coluna 'delivery_time': 47.43274712782266
Média da coluna 'minimumOrderValue': 276.89092923456997

In [19]:
df_sel["delivery_fee"].median()

6.0

In [20]:
df_sel[num].median()

delivery_fee          6.0
delivery_time        45.0
minimumOrderValue    15.0
dtype: float64

In [23]:
print("Média")
print(df_sel[num].mean())
print("--------------------")
print("Mediana")
print(df_sel[num].median())

Média
delivery_fee           6.804577
delivery_time         47.432747
minimumOrderValue    276.890929
dtype: float64
--------------------
Mediana
delivery_fee          6.0
delivery_time        45.0
minimumOrderValue    15.0
dtype: float64

In [24]:
df_sel["minimumOrderValue"].max()

99999999.99