# Calculando Amplitude

In [3]:
import pandas as pd

In [4]:
df = pd.read_csv("ifood-restaurants-february-2021.csv", sep=",", header=0)

In [5]:
df.head(5)

,availableForScheduling,avatar,category,delivery_fee,delivery_time,distance,ibge,minimumOrderValue,name,paymentCodes,price_range,rating,tags,url
0,False,https://static-images.ifood.com.br/image/uploa...,Marmita,3.99,27,1.22,5300108,10.0,Cantina Arte & Sabor,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ CART::MCHT::100_DELIVE...,https://www.ifood.com.br/delivery/brasilia-df/...
1,False,https://static-images.ifood.com.br/image/uploa...,Açaí,7.99,61,4.96,5300108,10.0,Raruty Açaí Raiz,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ ME...,https://www.ifood.com.br/delivery/brasilia-df/...
2,False,https://static-images.ifood.com.br/image/uploa...,Bebidas,11.99,70,8.35,5300108,5.0,Toma na Kombi,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ R...,MODERATE,0.0,ADDRESS_PREFORM_TYPE $$ CPGN_USER_DISCOUNT_6_L...,https://www.ifood.com.br/delivery/brasilia-df/...
3,False,https://static-images.ifood.com.br/image/uploa...,Carnes,16.49,63,6.35,5300108,20.0,Churrasquinho do Barriga´s,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ NO...,https://www.ifood.com.br/delivery/brasilia-df/...
4,False,https://static-images.ifood.com.br/image/uploa...,Brasileira,11.99,58,5.22,5300108,20.0,Prime Restaurante,DNR $$ MPAY $$ MOVPAY_MC $$ MC $$ GPY_ELO $$ E...,CHEAPEST,0.0,ADDRESS_PREFORM_TYPE $$ GUIDED_HELP_TYPE $$ NOVO,https://www.ifood.com.br/delivery/brasilia-df/...

In [11]:
num = df.select_dtypes(include=['number']).columns.tolist()

print('Variáveis Numéricas:', num)

Variáveis Numéricas: ['delivery_fee', 'delivery_time', 'distance', 'ibge', 'minimumOrderValue', 'rating']

In [12]:
# Remover a variável 'ibge' já que ela não atribui nenhum valor estatístico na análise

num.pop(3)

'ibge'

In [13]:
df[num].describe()

,delivery_fee,delivery_time,distance,minimumOrderValue,rating
count,406399.000000,406399.000000,406399.000000,4.063990e+05,406399.000000
mean,6.804577,47.432747,4.219752,2.768909e+02,2.522241
std,4.315815,19.662736,68.329379,1.570668e+05,2.286103
min,0.000000,-1.000000,0.000000,0.000000e+00,0.000000
25%,4.000000,35.000000,1.750000,1.000000e+01,0.000000
50%,6.000000,45.000000,3.080000,1.500000e+01,3.958900
75%,9.490000,60.000000,4.830000,2.000000e+01,4.718750
max,35.000000,5050.000000,11810.190000,1.000000e+08,5.000000